cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true
build:
  script:
    - echo $CI_PROJECT_DIR
    - npm install
    - rsync -a /home/gitlab-runner/builds/62fd03ed/0/app-vn/sns-vn-web /srv/
    - pm2 stop /srv/sns-vn-web/snsweb.js
    - pm2 start /srv/sns-vn-web/snsweb.js
  tags:
    - STAGING
  only:
    - staging
